# Base image
FROM quay.io/fedora/fedora:latest

# Metadata
LABEL maintainer="yourname@example.com"
LABEL description="PostgreSQL container with custom config and SSL certs"

# Environment variables
ENV PGDATA=/var/lib/pgsql/data
ENV CERTS=/etc/ssl/postgresql

# Create postgres user and group
RUN dnf install -y postgresql-server postgresql-contrib && \
    dnf clean all && \
    rm -rf /var/cache/dnf && \
    mkdir -p $PGDATA $CERTS /migrations /configs && \
    chown -R postgres:root $PGDATA $CERTS /migrations /configs

# Copy initialization scripts, configurations and set permissions
COPY --chown=root:root --chmod 644 certs/ca.crt /etc/ssl/ca.crt
COPY --chown=postgres:root --chmod 644 certs/server.crt $CERTS
COPY --chown=postgres:root --chmod 600 certs/server.key $CERTS
COPY --chown=postgres:root --chmod 600 pg_hba.conf postgres.conf /configs
COPY --chown=postgres:root --chmod 600 migrations/ /migrations
COPY --chown=root:postgres --chmod 750 entrypoint.sh /usr/local/bin/

# Set the user
USER postgres

# Working directory
WORKDIR /var/lib/pgsql

# Expose PostgreSQL default port
EXPOSE 5432

# Define volume for persistent storage
VOLUME ["$PGDATA"]

# Entrypoint script
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]